### ISSUE TITLE
Project directory isn't recognized as bazel project

### ISSUE THREAD

**Issue by davido** [bazelbuild/e4b#20] opened 2016-11-05 09:48 UTC
Trying to import bazel project itself or gerrit project, I'm getting this error message:

```
/home/davido/projects/gerrit does not seems to be a Bazel workspace
```

**Comment by davido** [comment] 2016-11-05 09:51
Ah, probably a duplicate of: #3 

`/usr/local/bin/bazel` isn't installed here.

```
$ which bazel
/home/davido/bin/bazel
davido@linux-ucwl:~/projects/bazel (master %=)$ /usr/local/bin/bazel
bash: /usr/local/bin/bazel: No such file or directory
```

In which case the error message is wrong.

I should have checked the console messages. It's saying:

```
*** Running [/usr/local/bin/bazel, --watchfs, info, workspace] from /home/davido/projects/bazel ***
*** Running [/usr/local/bin/bazel, --watchfs, info, workspace] from /home/davido/projects/gerrit ***
```

**Comment by damienmg** [comment] 2016-11-07 09:11
Yes it is indeed a dupe of #3

**Closed as completed by damienmg** 2016-11-07 09:11 UTC
